### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [bdshrk/neuraldrummer#1]
Hi there, 1st of all thanks for your awesome work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [AI-based projects page](https://github.com/forart/HyMPS/blob/main/AIaudio.md#--) \ [Drums subsection](https://github.com/forart/HyMPS/blob/main/AIaudio.md#drums-)), can you please add a "GH-compliant" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/bdshrk/neuraldrummer/?label=LICENSE)
(generative URL: https://flat.badgen.net/github/license/bdshrk/neuraldrummer/?label=LICENSE)

Anyway you can easily choose a "correct" one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by bdshrk** [comment]
Hi, I have added the MIT license to the repository.
I have just browsed your HyMPS project repository and the sorting of your collected projects seems pretty well done.

**Comment by MarcoRavich** [comment]
Thanks a lot, it works (and of course it's ranked higher on HyMPS) now.
